/**
* 
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Cable
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package me.emmano.state.comics.api

import kotlinx.serialization.Serializable


/**
 * 
 * @param path The directory path of to the image.
 * @param extension The file extension for the image.
 */
@Serializable
data class Image (
    /* The directory path of to the image. */
    val path: kotlin.String? = null,
    /* The file extension for the image. */
    val extension: kotlin.String? = null
) {

}
