/**
* 
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Cable
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.marvel.api


/**
 * 
 * @param type A description of the date (e.g. onsale date, FOC date).
 * @param date The date.
 */
data class ComicDate (
    /* A description of the date (e.g. onsale date, FOC date). */
    val type: kotlin.String? = null,
    /* The date. */
    val date: java.util.Date? = null
) {

}
