/**
* 
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Cable
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.marvel.api


/**
 * 
 * @param resourceURI The path to the individual event resource.
 * @param name The name of the event.
 */
data class EventSummary (
    /* The path to the individual event resource. */
    val resourceURI: kotlin.String? = null,
    /* The name of the event. */
    val name: kotlin.String? = null
) {

}
