/**
* 
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Cable
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.marvel.api


/**
 * 
 * @param id The unique ID of the event resource.
 * @param title The title of the event.
 * @param description A description of the event.
 * @param resourceURI The canonical URL identifier for this resource.
 * @param urls A set of public web site URLs for the event.
 * @param modified The date the resource was most recently modified.
 * @param start The date of publication of the first issue in this event.
 * @param end The date of publication of the last issue in this event.
 * @param thumbnail The representative image for this event.
 * @param comics A resource list containing the comics in this event.
 * @param stories A resource list containing the stories in this event.
 * @param series A resource list containing the series in this event.
 * @param characters A resource list containing the characters which appear in this event.
 * @param creators A resource list containing creators whose work appears in this event.
 * @param next A summary representation of the event which follows this event.
 * @param previous A summary representation of the event which preceded this event.
 */
data class Event (
    /* The unique ID of the event resource. */
    val id: Int? = null,
    /* The title of the event. */
    val title: kotlin.String? = null,
    /* A description of the event. */
    val description: kotlin.String? = null,
    /* The canonical URL identifier for this resource. */
    val resourceURI: kotlin.String? = null,
    /* A set of public web site URLs for the event. */
    val urls: List<Url>? = null,
    /* The date the resource was most recently modified. */
    val modified: java.util.Date? = null,
    /* The date of publication of the first issue in this event. */
    val start: java.util.Date? = null,
    /* The date of publication of the last issue in this event. */
    val end: java.util.Date? = null,
    /* The representative image for this event. */
    val thumbnail: Image? = null,
    /* A resource list containing the comics in this event. */
    val comics: ComicList? = null,
    /* A resource list containing the stories in this event. */
    val stories: StoryList? = null,
    /* A resource list containing the series in this event. */
    val series: SeriesList? = null,
    /* A resource list containing the characters which appear in this event. */
    val characters: CharacterList? = null,
    /* A resource list containing creators whose work appears in this event. */
    val creators: CreatorList? = null,
    /* A summary representation of the event which follows this event. */
    val next: EventSummary? = null,
    /* A summary representation of the event which preceded this event. */
    val previous: EventSummary? = null
) {

}
