/**
* 
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Cable
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.marvel.api


/**
 * 
 * @param type A text identifier for the URL.
 * @param url A full URL (including scheme, domain, and path).
 */
data class Url (
    /* A text identifier for the URL. */
    val type: kotlin.String? = null,
    /* A full URL (including scheme, domain, and path). */
    val url: kotlin.String? = null
)