# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVAIos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVAIos
  pod 'common', :path => '/Users/ortiguee/Android/android-mva/common'

  target 'MVAIosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVAIosUITests' do
    # Pods for testing
  end

end
